language: node_js
matrix:
  include:
  - node_js: 6
  - node_js: 8
  - node_js: 10
  - node_js: "lts/*"
  allow_failures:
  - node_js: 6
  - node_js: 8
install:
- npm install
- npm install -g gulp
- npm install -g gulp-cli
script:
- npm test

cache:
  directories:
  - "node_modules"

branches:
  only:
  - master
  - develop
