language: node_js
matrix:
  include:
  - node_js: "lts/*"
  - node_js: 11
  - node_js: 9
  - node_js: 8
  allow_failures:
  - node_js: 11
  - node_js: 9
  - node_js: 8
install:
  - npm install
  - npm install -g gulp
  - npm install -g gulp-cli
  - npm install -g jest
script:
  - npm run coverage:ci
  - npm run coverage:upload
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
  - develop
